name: Dependabot++

on:
  schedule:
    # Run every Sunday at 22:00 UTC (same as Dependabot)
    - cron: '0 22 * * 0'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  project-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup github actions bot
        uses: ./.github/workflows/setup-github-bot

      - name: Install environment
        uses: ./.github/workflows/env-install

      - name: Upgrade project
        id: upgrade
        run: uv run poe project:upgrade_ci

      - name: Create Pull Request
        if: steps.upgrade.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.upgrade.outputs.commit_message }}
          branch: ${{ steps.upgrade.outputs.branch }}
          delete-branch: true
          signoff: true
          title: ${{ steps.upgrade.outputs.title }}
          body: ${{ steps.upgrade.outputs.body }}
          labels: |
            dependencies
          assignees: ${{ github.repository_owner }}
